/**
 * @brief Implementation of The Statistics class. A class that holds the tables of correct moves for blackjack
 *
 * @authors Noah Zaffos, Caleb Standfield, Ethan Perkins, Jas Sandhu, Nash Hawkins, John Chen
 * @date 4/20/2025
 */

#include "statistics.h"

const MOVE Statistics::HardTable[17][10] = {
    {MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                               // Hard 5
    {MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                               // Hard 6
    {MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                               // Hard 7
    {MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                               // Hard 8
    {MOVE::HIT, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                   // Hard 9
    {MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::HIT, MOVE::HIT},       // Hard 10
    {MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE}, // Hard 11
    {MOVE::HIT, MOVE::HIT, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                         // Hard 12
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                     // Hard 13
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                     // Hard 14
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                     // Hard 15
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                     // Hard 16
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND},           // Hard 17
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND},           // Hard 18
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND},           // Hard 19
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND},           // Hard 20
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND}            // Hard 21
};

const MOVE Statistics::SoftTable[9][10] = {
    {MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                // A,2
    {MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                // A,3
    {MOVE::HIT, MOVE::HIT, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},             // A,4
    {MOVE::HIT, MOVE::HIT, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},             // A,5
    {MOVE::HIT, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},          // A,6
    {MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::STAND, MOVE::STAND, MOVE::HIT, MOVE::HIT, MOVE::HIT},   // A,7
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::DOUBLE, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND}, // A,8
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND},  // A,9
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND}   // A,10 (multi-card soft 21)
};

const MOVE Statistics::PairTable[10][10] = {
    {MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},             // 2,2
    {MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},             // 3,3
    {MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},                     // 4,4
    {MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::DOUBLE, MOVE::HIT, MOVE::HIT}, // 5,5
    {MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},               // 6,6
    {MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::HIT, MOVE::HIT, MOVE::HIT, MOVE::HIT},             // 7,7
    {MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT},     // 8,8
    {MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::STAND, MOVE::SPLIT, MOVE::SPLIT, MOVE::STAND, MOVE::STAND},     // 9,9
    {MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND, MOVE::STAND},     // 10,10 (10, J, Q, K)
    {MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT, MOVE::SPLIT}      // A,A
};

Statistics::Statistics()
{
}
